### ISSUE TITLE
Add flux suspend/resume for source

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/orange-cf-bosh-cli#101]
It could be nice to be able to manage git repositories like kustomizations or helmrelease.

We should be able to do this by adding the config below:

```
toggle-sources:
    shortCut: Shift-T
    confirm: true
    scopes:
      - gitrepo
    description: Toggle to suspend or resume a Git repository
    command: sh
    background: false
    args:
      - -c
      - "flux --context $CONTEXT $([ $(kubectl --context $CONTEXT get gitrepo -n $NAMESPACE $NAME -o=custom-columns=TYPE:.spec.suspend | tail -1) = \"true\" ] && echo \"resume\" || echo \"suspend\") source git -n $NAMESPACE $NAME | less"
```
