### ISSUE TITLE
kubeconfig edition with http_proxy

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#109]
## expected behavior

As a bosh-cli user
in order to use the kubeconfig generated by log-k8s through an http_proxy
I need the kubeconfig to be edited automatically to insert `proxy-url` directive documented at https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#proxy for each cluster

for instance
```
log-k8s -p http://localhost:8888 
```
would generate an additional modified ~/.kube/config-with-proxy file with the  `proxy-url` with

```yaml
apiVersion: v1
kind: Config

clusters:
- cluster:
    proxy-url:  http://localhost:8888
    server: https://k8s.example.org/k8s/clusters/c-xxyyzz
  name: development

users:
- name: developer

contexts:
- context:
  name: development
```

## current behavior

log-k8s does not yet support a -p option
