### ISSUE TITLE
Add flux reconcile k9s shortcuts for helmrepo + ocirepo

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#131]
Additions to .k9s/plugins.yaml

```yaml
  reconcile-helm-repo:
    shortCut: Shift-Z
    description: Flux reconcile
    scopes:
      - helmrepositories
    command: bash
    background: false
    confirm: false
    args:
      - -c
      - "flux reconcile source helm --context $CONTEXT -n $NAMESPACE $NAME |& less"
  reconcile-oci-repo:
    shortCut: Shift-Z
    description: Flux reconcile
    scopes:
      - ocirepositories
    command: bash
    background: false
    confirm: false
    args:
      - -c
      - "flux reconcile source oci --context $CONTEXT -n $NAMESPACE $NAME |& less"
```
