### ISSUE TITLE
K9s helm get all shortcut

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#138]
In order to easily get the output of the `helm get all <chart>`

$ helm get all crossplane -n 70-crossplane --help

This command prints a human readable collection of information about the
notes, hooks, supplied values, and generated manifest file of the given release.

> Usage:
>   helm get all RELEASE_NAME [flags]
> 
> Flags:
>   -h, --help              help for all
>       --revision int      get the named release with revision
>       --template string   go template for formatting the output, eg: {{.Release.Name}}
> 
> Global Flags:
>       --debug                       enable verbose output
>       --kube-apiserver string       the address and the port for the Kubernetes API server
>       --kube-as-group stringArray   group to impersonate for the operation, this flag can be repeated to specify multiple groups.
>       --kube-as-user string         username to impersonate for the operation
>       --kube-ca-file string         the certificate authority file for the Kubernetes API server connection
>       --kube-context string         name of the kubeconfig context to use
>       --kube-token string           bearer token used for authentication
>       --kubeconfig string           path to the kubeconfig file
>   -n, --namespace string            namespace scope for this request
>       --registry-config string      path to the registry config file (default "/data/shared/gberche/helm/registry/config.json")
>       --repository-cache string     path to the file containing cached repository indexes (default "/data/shared/gberche/.cache/helm/repository")
>       --repository-config string    path to the file containing repository names and URLs (default "/data/shared/gberche/helm/repositories.yaml")
> 

```yaml
plugin: 
  helm-get-all:
    shortCut: Shift-K
    description: Helm Get All
    scopes:
    # Unable to scope only to built in helm releases: key binding if ineffective when specifying chart of Helm. Therefore scoping all as a workaround
      - all
    command: bash
    background: false
    confirm: true
    args:
      - -c
      - "helm get all ${NAME} -n $NAMESPACE| less"
```
