### ISSUE TITLE
Add kubectl login helper

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#40]
As a paas-template operator, in order to act onto K8S, I need an efficient way to login into K8S

/CC @obeyler

**Comment by obeyler** [comment]
current workaround:
create file "config" into ~/.kube/
content of the file replace ((env)) by either micro or master or kubo depending the k8s:
```
- cluster:
    insecure-skip-tls-verify: true
    server: https://cfcr-api-micro.internal.paas
  name: cfcr-micro

- cluster:
    insecure-skip-tls-verify: true
    server: https://cfcr-api-master.internal.paas
  name: cfcr-master

- cluster:
    insecure-skip-tls-verify: true
    server: https://cfcr-api-ops.internal.paas
  name: cfcr-ops

contexts:
- context:
    cluster: cfcr-micro
    user: cfcr-micro-admin
  name: cfcr-micro
- context:
    cluster: cfcr-master
    user: cfcr-master-admin
  name: cfcr-master
- context:
    cluster: cfcr-ops
    user: cfcr-ops-admin
  name: cfcr-ops

current-context: cfcr-ops
kind: Config
preferences: {}
users:
- name: cfcr-micro-admin
  user:
    token: xxxxx ## needs to be replace by value of credhub get -n /micro-depls/cfcr/kubernetes-password
- name: cfcr-master-admin
  user:
    token: xxxxx ## needs to be replace by value of credhub get -n /master-depls/cfcr/kubernetes-password
- name: cfcr-ops-admin
  user:
    token: xxxxx ## needs to be replace by value of credhub get -n /kubo-depls/cfcr/kubernetes-password
```
